### PR TITLE
Adding publicDeltaCore env var to frontend

### PR DESCRIPTION
**Pull request by opishcheiko**
not sure if that's correct, but adding PUBLIC_DELTA_CORE_URL to both dev and prod docker-compose

### CODE REVIEW

**Comment by Jnegrier** [comment]
> not sure if that's correct, but adding PUBLIC_DELTA_CORE_URL to both dev and prod docker-compose

Hi Sasha, actually the public URL for the core service running locally like in this case would be `http://localhost:5000`

**Comment by opishcheiko** [comment]
> > not sure if that's correct, but adding PUBLIC_DELTA_CORE_URL to both dev and prod docker-compose
> 
> Hi Sasha, actually the public URL for the core service running locally like in this case would be `http://localhost:5000`

@Jnegrier can I put `http://delta_core:5000` for the dev, in case I am not running my backend on localhost? And for prod it will be `https://delta-core.dsch.dev/` one, right?

**Comment by Jnegrier** [comment]
> > > not sure if that's correct, but adding PUBLIC_DELTA_CORE_URL to both dev and prod docker-compose
> > 
> > 
> > Hi Sasha, actually the public URL for the core service running locally like in this case would be `http://localhost:5000`
> 
> @Jnegrier can I put `http://delta_core:5000` for the dev, in case I am not running my backend on localhost? And for prod it will be `https://delta-core.dsch.dev/` one, right?

In that case you can change the value to the one were the backend is running :) but since we want these docker-compose files to run a ready to use Delta Reporter for any person, we should just leave the value in the repo as `http://localhost:5000`for both dev and prod.

The `dsch.dev` is for internal use only, so it should be updated in a private repo for helm deployments

**Comment by opishcheiko** [comment]
> > > > not sure if that's correct, but adding PUBLIC_DELTA_CORE_URL to both dev and prod docker-compose
> > > 
> > > 
> > > Hi Sasha, actually the public URL for the core service running locally like in this case would be `http://localhost:5000`
> > 
> > 
> > @Jnegrier can I put `http://delta_core:5000` for the dev, in case I am not running my backend on localhost? And for prod it will be `https://delta-core.dsch.dev/` one, right?
> 
> In that case you can change the value to the one were the backend is running :) but since we want these docker-compose files to run a ready to use Delta Reporter for any person, we should just leave the value in the repo as `http://localhost:5000`for both dev and prod.
> 
> The `dsch.dev` is for internal use only, so it should be updated in a private repo for helm deployments

okay, I am confused. Changed both to localhost

**Pull request merged**
